config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root 'sessions#new'
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show]
  resources :conversations do
    resources :messages
  end
  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, {presence: true, length: {maximum: 140}}
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  def new
    @blog = Blog.new
  end
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end
  def show
    @comments = @blog.comments
    @comment = @blog.comments.build
  end
  def edit
  end
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?

  end
  private
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <p><%= form.label :写真 %></p>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="blog_content">
    <%= form.text_area :content,'data-provider': :summernote,id:"summernote"%>
    <%#form.text_area :content, placeholder: "いまなにしてる？", size: "30x10" %>
  </div>
  <p><%= form.submit %></p>
  <%= link_to 'ホームへ', blogs_path %>
<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で投稿する。</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>内容:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2 class="edit_page">編集する<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<main>
  <h1 class="post_list">投稿一覧<span class="glyphicon glyphicon-ok" aria-hidden="true"></span></h1>
  <p><%= notice %></p>
  <% @blogs.each do |blog| %>
    <table class="post_table">
      <tr>
        <td>名前：<%= blog.user.name %></td>
      </tr>
      <tr>
        <td><%= image_tag blog.image.url unless blog.image.file.nil? %></td>
      </tr>
      <tr>
        <td><内容><br><%= blog.content %></td>
      </tr>
      <tr class="edit">
      <td><%= link_to '詳細', blog_path(blog.id) %>
      <%= link_to "編集", edit_blog_path(blog.id) %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data:{confirm: '本当に削除しますか？'} %></td>
      </tr>
    </table>
  <% end %>
  <div class="newly_posts">
    <p><span class="label label-default">New</span></p>
    <p class="home_posts_button"><%= link_to '投稿する', new_blog_path %></P>
  </div>
</main>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="verbose_screen">
  <h1>詳細画面</h1>
  <p>写真</p>
  <p><%= image_tag(@blog.image.url, size: "400x500") unless @blog.image.file.nil? %></p>
  <p><内容></p>
  <p><%= @blog.content %></p>
  <p>ーーコメント一覧ーー</p>
  <!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
  <div id="comments_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
  </div>
  <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
  <%= link_to '一覧へ', blogs_path %>
</div>