config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root 'sessions#new'
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show]
  resources :conversations do
    resources :messages
  end
  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
    <li><%= render 'follow_form', user: user %></li> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="account_creating">
  <h1>アカウント登録</h1>
  <p>簡単に登録できます。</p>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <table class="account_creating_form">
      <tr>
        <td><%= f.text_field :name, placeholder: "名前"%></td>
      </tr>
      <tr>
        <td><%= f.email_field :email, placeholder: "メールアドレス"  %></td>
      </tr>
      <tr>
        <td><%= f.password_field :password, placeholder: "パスワード" %></td>
      </tr>
      <tr>
        <td><%= f.password_field :password_confirmation, placeholder: "パスワード(再確認)" %></td>
      </tr>
      <tr>
        <td><%= f.submit "アカウント登録" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="login_success">
  <h1><%= @user.name %>のページ</h1>
  <p>メールアドレス: <%= @user.email %></p>
  <p><%= link_to 'ホーム', blogs_path %></p>
  <p><%= link_to '新しくブログを投稿する', new_blog_path %></p>
</div>